spacecubics/www

- README.md
We use Montserrat for Latin and numeric glyphs, and Zen Kaku Gothic
New for Japanese glyphs. This distinction is based on language, not on
primary versus secondary fonts.
> README: Fix typography description

- content/about_us/_index.en.md
- content/about_us/_index.md
- content/recruit/_index.en.md
- content/recruit/_index.md
fix(prefooter text): ensure last recruit page prefooter card is consistent with designer's specified design.
The last prefooter card on the "Recruit" page was inconsistent with other pages, where "contact" is always the last box. This change aligns with the designer's specifications. Additionally, prefooter text for About Us and Products was also corrected in line with designer specifications (English and Japanese).
BEFORE:
AFTER:
This fixes #6
> Issue #6: Correct "Recruit" page prefooter text (Products, About Us, and Contact)

- config.toml
- templates/shortcodes/application_form.html
- templates/shortcodes/contact_form.html
- Remove config.extra.captcha_site_key from config.toml
- Use get_env built-in Tera engine function in HTML
- Make matching change in README.md
- Coordinate with @takumiando to use `zola build` rather than `build.sh` on Cloudflare.
This closes #16
> captcha: use get_env method

- content/products/_index.en.md
- content/products/_index.md
- templates/shortcodes/product_display.html
- add "Zephyr RTOS GitHub Repository" + link
- change "User Manual" to "Space Cubics Documentation"
- change "Zephyr Docs" to "Zephyr Project Documentation"
- change "GitHub" to "Space Cubics GitHub"
- make product_display documentation block DRY
This fixes #54
> fix: documentation URLs

- content/about_us/_index.en.md
- content/about_us/_index.md
- sass/_board_members.scss
- static/blocks/board-members.json
- templates/shortcodes/board_members.html
Move data to static/blocks/board-members.json to load structured data at render time. This reduces the size of the board_member shortcode by half without losing functionality.
> templates: shortcodes: Simplify board_members

- config.toml
Zola's default behavior is to slugify the file names. It's confusing at best. In fact, the links to the about_us page were broken.
We don't really care about SEO. So, disable it.
> config.toml: Disable slugify

- sass/_news_article.scss
- templates/news_article.html
Re-design news article template
Revise news_article.html and .scss
- Add section title
- Implement basic centered layout
- Add "Back to List" text and button
- Auto-include contact prefooter card
BEFORE:
AFTER:
This fixes #107 
`page.content | safe`  is used in news_article.html line 19 because of text corruption.
With `| safe `:
Without `| safe` :
> News article template is not done

- content/news/_index.en.md
- content/news/_index.md
Remove the empty `[extra]` table from the front matter of the index.
> content: news: Remove empty extra from the front matter

- sass/_splash.scss
- templates/shortcodes/splash.html
Replace duplicate splash.html SVGs with those from config.toml for simplicity.
Add styling for these changes and better
mobile screen centering.
This fixes #125
> Fix: use config.toml inline SVG icons in splash footer

- sass/_sc-list.scss
- sass/style.scss
- templates/partials/news_list_block.html
- Create reusable style file `_sc-list.scss` following BEM methodology.
- Revise `news_list_block.html` to use `sc-list` styling.
This fixes #119 
`_sc-list.scss` can be used in other parts of the site with lists.
> Fix: inconsistent gap between news list dates and titles

- content/recruit/software_engineer/index.en.md
- content/recruit/software_engineer/index.md
- sass/_about_company.scss
- sass/_application_form.scss
- sass/_board_members.scss
- sass/_docs_resources.scss
- sass/_footer.scss
- sass/_hero_element.scss
- sass/_jobs_list.scss
- sass/_language_switcher.scss
- sass/_nav.scss
- sass/_news_article.scss
- sass/_prefooter.scss
- sass/_price.scss
- sass/_price_supp.scss
- sass/_product_display.scss
- sass/_recruit_intro.scss
- sass/_sc-list.scss
- sass/_splash.scss
- sass/_tagline.scss
- sass/_threecard.scss
- sass/_title.scss
- sass/_typography.scss
- templates/partials/head.html
Fix text anomaly seen when using -webkit-text-stroke above 2px. Solution is to update font weight import in head.html following Google CSS API, then remove -webkit-text-stroke in problematic blocks.
Also revise font-weight in some scss files to approximate initial design. Webkit-text-stroke was used to make text bolder, but also changed letter shape.
This fixes #147 
Webkit altered the shape of the letters. Removing webkit returned some text to native size.
[Screencast from 2025-08-08 12-34-05.webm](https://github.com/user-attachments/assets/6db7548f-cb1f-42d1-8ff2-27ff5862759a)
> fix: remove text anomaly due to font weight conflicts

- templates/shortcodes/hero_element.html
- templates/shortcodes/product_display.html
get_url behaves differently depending on the "@/” prefix: without it, it uses the site’s default language from the config; with it, it does not. After 812101c55ce58d6 switched local links to "@/”, internal page links started resolving to the wrong language and broke.
Make the shortcode resolve links consistently regardless of the prefix.
This fixes #170.
> templates: shortcodes: Fix get_url language handling with "@/”

- i18n/en.toml
- i18n/ja.toml
- templates/article.html
- templates/base.html
- templates/partials/articles.html
Remove references to the unused variable `date_locale` associated with the macro `translate.html`. 
These references remain from a previous version of the macro, and their removal does not affect date format translation.
This fixes #58 and is associated with https://github.com/spacecubics/www/pull/141.
> macro: translate: remove unused date_locale variable

- content/products/scobc_a1.en.md
- content/products/scobc_a1.md
Add link to software manual in JP and EN versions of scobc-a1 page.
This fixes #181
> docs: scobc-a1: add software manual link

- content/about_us.en.md
Replace the Japanese text in the English About Us page by pointing to blocks/about_company.en.json.
This fixes #214
> i18n: fix: Replace JA text in about_us.en.md

- content/products/scobc_a1.md
Fix the contact form link by removing typo text in `scobc_a1.md`. 
Error only seen in Japanese version of `price_supp` section.
This fixes #224
> link: fix broken contact link in scobc_a1 page

- sass/_article-list.scss
- sass/_code.scss
- sass/_external.scss
- sass/_feed.scss
- sass/_footer.scss
- sass/_iframe.scss
- sass/_input.scss
- sass/_nav.scss
- sass/_normalize.scss
- sass/_threecard.scss
- sass/_typography.scss
- sass/_zola-anchor.scss
Removed all uses of `-webkit` from `scss` files.
This fixes #149 
One visual change in Space One (partners) logo on mobile.
I think this is a visual improvement, so I proceeded with PR.
| Before | After |
|--------|-------|
| <img width="522" height="814" alt="Screenshot from 2025-08-25 14-28-28" src="https://github.com/user-attachments/assets/c5e3f7ae-e6ee-4395-9441-1939e1d002e3" /> | <img width="522" height="814" alt="Screenshot from 2025-08-25 14-28-23" src="https://github.com/user-attachments/assets/20148792-d336-4a21-a373-bc2b31b313b5" /> |
> Remove all CSS property with -webkit prefix

- functions/contact.js
- static/js/contact.js
- templates/shortcodes/application_form.html
- Revise `functions/contact.js` to use map of webhooks based on form ID.
- Revise `js/contact.js` to send `form_id` in payload.
- Revise `application_form.html` form id to `"recruitForm"`.
This fixes #200
> Separate the form into a contact form and a recruitment form

- .cloudflare-build.sh
We want to set base URL as ```https://<hash>.spacecubics.pages.dev``` in preview builds.
This method is described at the following page:
https://developers.cloudflare.com/pages/framework-guides/deploy-a-zola-site/
> .cloudflare-build.sh: Use ```CF_PAGES_URL``` in preview builds

- README.md
Clarify that contributors should not use two trailing spaces for line breaks, since they are hard to detect and programmers generally avoid trailing whitespace. Instead, recommend using an explicit `<br>` tag.
> README: Document preferred line break style

- .github/workflows/visual-regression-test.yml
Use zola built-in build option `--base-url` instead of `sed` in `visual-regression-test.yml`.
The `sed` method alters `config.toml` and can cause issues during PR checkout.
This fixes #244 
Validation test:
https://www.notion.so/Playwright-CI-Setup-26062e4c3fd0805a8f34c4a36b3d98aa?pvs=25
> test: use zola build --base-url in VRT workflow

- .github/workflows/visual-regression-test.yml
VRT comments indicate whether visual regression tests succeeded, but PRs from forks run with read-only tokens, causing comment attempts to fail with 403 errors. As a quick workaround, disable commenting on forked PRs.
Ideally, VRT and commenting should run in separate workflows—VRT can run on any PR (requires only read access), while commenting should be restricted to the base repository.
To receive VRT comments, open the PR from a branch within this repository instead of from a fork.
This fixes #255.
> .github: workflows: vrt: disable commenting for PRs from forks

- sass/_general.scss
Hide x-axis overflow for hero-section, splash, banner, and site-footer in _general.scss.
This fixes the extra right-side space in homepage `fullPage` snapshots
- Homepage snapshots fail as expected.
- Mobile snapshots unaffected.
> scss: add overflow-x: hidden; to exceptions in _general.scss
