- README.md
- README.md
- Removed unused doc/wiki reference
- Simplified file tree explanation
- Removed redundant information
- Added example of Tera syntax rules
Cause:  the removal of `build.sh`?
SC employee with access to Cloudflare account should revise the build instructions. 
During early testing, I found Cloudflare's built-in `zola build` command did not work (so I created `build.sh`).
Reading other users' posts showed same issue (`zola build` did not deploy correctly) -- maybe fixed now?
> README: more clean content

- .github/workflows/gitlint.yml
- .github/workflows/linelint.yaml
- .gitlint
- .linelint.yml
See each commit for more details.
> Add two check on github actions

- sass/_general.scss
- sass/_hero_element.scss
- Fix hero image background scaling
- delete lint from _general.scss
- removed unnecessary width settings from _hero_element.scss
This fixes #27 
[Screencast from 2025-07-20 12-46-12.webm](https://github.com/user-attachments/assets/a85c01c0-10a1-4092-bec7-c1ded9c0583e)
> Image scaling is odd #27

- sass/_board_members.scss
- sass/_general.scss
- sass/_nav.scss
- sass/_splash.scss
make main content 1100px in width across screen sizes
- set main content to 1100px width in _general.scss
- add exceptions for splash-image, hero bg-img, and footer
- adjust styling on _board_member.scss
This fixes #56
> Contents must be fixed at 1100px width #56

- templates/partials/head.html
Load web fonts we are using. Without these lines, browsers won't use them.
> templates: partials: head: Load fonts

- content/about_us/_index.en.md
- content/about_us/_index.md
- content/contact/_index.en.md
- content/contact/_index.md
- content/ir_info/_index.en.md
- content/ir_info/_index.md
- content/news/_index.en.md
- content/news/_index.md
- content/products/_index.en.md
- content/products/_index.md
- content/recruit/_index.en.md
- content/recruit/_index.md
- content/sc_obc/_index.en.md
- content/sc_obc/_index.md
- templates/section.html
See each commit message for more details.
> Update and fix templates

- content/about_us.en.md
-added tagline with En translation to about_us.en.md
> add tagline to English about_us page

- content/_index.en.md
- content/_index.md
Remove alt string "Diagram" for the image of SC-OBC module A1. The string doesn't add anything to it.
> content: Remove alt string "Diagram"

- README.md
Update the instructions for adding a new news article.
This fixes #114
> Revise: readme: update new news article

- README.md
- doc/develop.md
Our RAEDME file is getting larger. Most of the topics are not need for casual committers who just add a new news article. This PR update README and move developer related topics under doc/develop.md.
See each commit log for more details.
> Update and tweak README and co

- i18n/ja.toml
- templates/article.html
- templates/article_list.html
- templates/job_post.html
- templates/news_article.html
- templates/partials/articles.html
- templates/partials/news_list_block.html
- templates/recruit_list.html
Apply date format defined in en.toml and ja.toml to news lists and news articles.
> news_article.html: news_list_block.html: apply date_format

- content/recruit/_index.en.md
- content/recruit/_index.md
- templates/shortcodes/jobs_list.html
We don't need this special note. Remove it.
> content: recruit: Remove special note

- doc/develop.md
There are some differences in HTTP servers we use. Make sure we all know about it.
> doc: develop: Add a new section Server Behavior Differences

- templates/news_article.html
- templates/news_section.html
- templates/page.html
- templates/partials/news_list.html
- templates/partials/section_title.html
- templates/section.html
- templates/shortcodes/section_title.html
See commit logs for more details
> Remove style top

- content/products/scobc_a1.en.md
- content/products/scobc_a1.md
For the special price, tax is not included.
This fixes #178.
> content: products: a1: price: Tax not included

- templates/404.html
- templates/base.html
- templates/index.html
- templates/partials/language_switcher.html
- templates/partials/title.html
See each commit log for more details.
> 404 update

- .mailmap
I don't know how many identities he has, but here we go.
> .mailmap: Add yet another eric

- README.md
- netlify.toml
- `netlify.toml` deleted
- reference to `netlify.toml` removed from `README.md`.
> Remove netlify.toml

- .github/workflows/visual-regression-test.yml
This fixes #249 
Current solution: auto-generated warning message in PR discussion thread
Validation notes: https://www.notion.so/spacecubics/Playwright-CI-Setup-26062e4c3fd0805a8f34c4a36b3d98aa
> test: Add warning for VRT test failure

- playwright.config.ts
- tests/visual-regression-test.spec.ts
see each commit log for more details.
> Playwright config update

- content/news/2025-09-26.en.md
- content/news/2025-09-26.md
This is news for exhibition at Hokkaido Space Summit 2025.
> news: 2025-09-26: Exhibition at Hokkaido Space Summit 2025
